---
- name: Add Accumulo user to HDFS supergroup
  user: name=accumulo
        append=yes
        group=hadoop
        state=present

- name: Configure Accumulo
  template: src={{ item }}.j2
            dest={{ accumulo_conf_dir }}/{{ item }}
            mode=0644
  with_items:
    - accumulo-env.sh
    - accumulo-metrics.xml
    - accumulo-site.xml
    - generic_logger.xml
    - log4j.properties
    - monitor_logger.xml
  notify:
    - Restart Accumulo Leader
    - Restart Accumulo Monitor
    - Restart Accumulo Tracer
    - Restart Accumulo Garbage Collector
    - Restart Accumulo Tablet Server

- name: Check if Accumulo has been initialized
  command: "hadoop fs -test -d /accumulo"
  sudo_user: hdfs
  register: accumulo_initialized
  changed_when: accumulo_initialized.rc == 1
  failed_when: False
  when: accumulo_leader

- name: Initialize Accumulo
  command: "accumulo init --instance-name {{ accumulo_secret }} --password {{ accumulo_secret }}"
  sudo_user: accumulo
  when: accumulo_initialized | changed
  notify:
    - Restart Accumulo Leader
    - Restart Accumulo Monitor
    - Restart Accumulo Tracer
    - Restart Accumulo Garbage Collector
    - Restart Accumulo Tablet Server

- name: Set system swappiness
  copy: content="{{ accumulo_leader_host }}"
        dest="{{ accumulo_conf_dir }}/masters"
        mode=0644
