---
- name: Get rid of joda-time
  file: path={{ item }} state=absent
  with_items:
    - /usr/lib/hadoop/client/joda-time-1.6.jar
    - /usr/lib/hadoop/client/joda-time.jar
    - /usr/lib/hadoop-mapreduce/joda-time-1.6.jar
    - /usr/lib/parquet/lib/joda-time-1.6.jar
