---
- name: Remove 127.0.1.1 from /etc/hosts
  lineinfile: dest="/etc/hosts"
              regexp="^127.0.1.1"
              line=""
              state=absent
  when: developing

- name: Increase ulimits
  lineinfile: dest="/etc/security/limits.conf"
              regexp="{{ item }} nofile"
              line="* {{ item }} nofile 65536"
  with_items:
    - soft
    - hard

- name: Set system swappiness
  copy: content="vm.swappiness = 0"
        dest=/etc/sysctl.d/10-swappiness.conf
        mode=0644
  notify:
    - Update sysctl
