---
- hosts: leaders
  sudo: True

  roles:
    - { role: "geotrellis-spark-cluster.accumulo", accumulo_leader: True }

- hosts: followers
  sudo: True

  roles:
    - { role: "geotrellis-spark-cluster.accumulo", accumulo_leader: False }
