---
- hosts: leaders
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "geotrellis-spark-cluster.common" }
    - { role: "azavea.pptpd", when: packing }
    - { role: "geotrellis-spark-cluster.graphite" }
    - { role: "geotrellis-spark-cluster.grafana" }
    - { role: "geotrellis-spark-cluster.mesos", mesos_leader: True }
    - { role: "geotrellis-spark-cluster.ipython" }
    - { role: "geotrellis-spark-cluster.cleanup" }
